### ISSUE TITLE
Skipped unit tests

### ISSUE THREAD

**Issue by Zauberstuhl** [diaspora/vines#68]
There are multiple tests which are marked as 'skipped'. Please investigate and try to find a solution for them

**Comment by Zauberstuhl** [comment]
```bash
Vines::Cluster::Publisher::#route#test_0001_publishes the message to just one cluster node:
MockExpectationError: No more expects available for :id: []
    /home/lukas/workspace/vines/lib/vines/cluster/publisher.rb:34:in `route'
    /home/lukas/workspace/vines/test/cluster/publisher_test.rb:37:in `block (3 levels) in <top (required)>'
```

There is another one breaking randomly
