### ISSUE TITLE
Test failing

### ISSUE THREAD

**Issue by balasankarc** [diaspora/vines#78]
One of the tests seem to fail. See log below. Any help in solving this would be appreciated.
```
$ bundle install  
Resolving dependencies...
Using rake 10.4.2
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.8.0
Using thread_safe 0.3.5
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile 0.6.2
Using rack 1.6.4
Using mime-types 2.6.1
Using arel 6.0.3
Using addressable 2.3.8
Using ast 2.0.0
Using bcrypt 3.1.10
Using bundler 1.11.2
Using eventmachine 1.0.9.1
Using hiredis 0.6.1
Using http_parser.rb 0.6.0
Using multipart-post 2.0.0
Using multi_xml 0.5.5
Using terminal-table 1.5.2
Using powerpack 0.1.1
Using rugged 0.22.2
Using thor 0.19.1
Using rainbow 2.0.0
Using ruby-progressbar 1.7.5
Using sqlite3 1.3.10
Using tzinfo 1.2.2
Using nokogiri 1.6.6.2
Using rack-test 0.6.3
Using sprockets 3.3.2
Using mail 2.6.3
Using parser 2.2.2.5
Using em-hiredis 0.3.1
Using faraday 0.9.1
Using httparty 0.13.5
Using activesupport 4.2.3
Using loofah 2.0.3
Using astrolabe 1.3.0
Using sawyer 0.6.0
Using gitlab 3.4.0
Using rails-deprecated_sanitizer 1.0.3
Using globalid 0.3.6
Using activemodel 4.2.3
Using rails-html-sanitizer 1.0.2
Using rubocop 0.32.0
Using octokit 3.8.0
Using rails-dom-testing 1.0.7
Using activejob 4.2.3
Using activerecord 4.2.3
Using pronto 0.4.2 from https://github.com/Zauberstuhl/pronto.git (at master@292d8ac)
Using actionview 4.2.3
Using diaspora-vines 0.2.0.develop.4 from source at `.`
Using pronto-rubocop 0.4.4
Using actionpack 4.2.3
Using actionmailer 4.2.3
Using railties 4.2.3
Using sprockets-rails 2.3.2
Using rails 4.2.3
Bundle complete! 7 Gemfile dependencies, 59 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.


$ bundle exec rake
Was not able to load config/application.rb! This not a standalone version. You should use it only in a diaspora environment.
Was not able to load config/load_config.rb! This not a standalone version. You should use it only in a diaspora environment.
Was not able to load config/initializers/devise.rb! This not a standalone version. You should use it only in a diaspora environment.
Run options: --seed 55337

# Running:

..............................S..................................................................................................................................S..S............S............................................................................................................................................................................................................................................E..............

   1) handles invalid input
      NoMethodError: undefined method `ascii_only?' for nil:NilClass
          /usr/lib/ruby/2.2.0/openssl/ssl.rb:172:in `verify_hostname'
          /usr/lib/ruby/2.2.0/openssl/ssl.rb:161:in `block in verify_certificate_identity'
          /usr/lib/ruby/2.2.0/openssl/ssl.rb:159:in `each'
          /usr/lib/ruby/2.2.0/openssl/ssl.rb:159:in `verify_certificate_identity'
          /home/balasankarc/packaging/trying/diaspora-vines/original/vines/lib/vines/store.rb:126:in `block (2 levels) in files_for_domain'
          /home/balasankarc/packaging/trying/diaspora-vines/original/vines/lib/vines/store.rb:125:in `each'
          /home/balasankarc/packaging/trying/diaspora-vines/original/vines/lib/vines/store.rb:125:in `block in files_for_domain'
          /home/balasankarc/packaging/trying/diaspora-vines/original/vines/lib/vines/store.rb:124:in `each'
          /home/balasankarc/packaging/trying/diaspora-vines/original/vines/lib/vines/store.rb:124:in `files_for_domain'
      # /usr/lib/ruby/2.2.0/openssl/ssl.rb:172
      # /usr/lib/ruby/2.2.0/openssl/ssl.rb:161
      # /usr/lib/ruby/2.2.0/openssl/ssl.rb:159
      # /usr/lib/ruby/2.2.0/openssl/ssl.rb:159
      # lib/vines/store.rb:126
      # lib/vines/store.rb:125
      # lib/vines/store.rb:125
      # lib/vines/store.rb:124
      # lib/vines/store.rb:124
      # test/store_test.rb:41

   2) raises a service-unavailable stanza error [SKIPPED]
      test/stanza/message_test.rb

   3) save fragment [SKIPPED]
      test/storage/sql_test.rb

   4) find fragment [SKIPPED]
      test/storage/sql_test.rb

   5) writes the stanza to the connected user streams [SKIPPED]
      test/cluster/subscriber_test.rb

Finished in 6.845142s, 62.6722 runs/s, 136.3010 assertions/s.
429 runs, 933 assertions, no failures, 1 error, 4 skips

Failed Tests:

rake TEST=/home/balasankarc/packaging/trying/diaspora-vines/original/vines/test/store_test.rb TESTOPTS="--name=test_0001_handles invalid input"

After_run hook deleted test.db
rake aborted!
Command failed with status (1): [ruby -I"lib:test:test/storage" -I"/usr/lib/ruby/vendor_ruby" "/usr/lib/ruby/vendor_ruby/rake/rake_test_loader.rb" "test/**/*_test.rb" ]

Tasks: TOP => default => test
(See full trace by running task with --trace)

```

**Comment by Zauberstuhl** [comment]
@balasankarc you probably haven't  configured your certs here `conf/certs/` ?!

**Comment by balasankarc** [comment]
Ah. I didn't know it was required even for running tests. Lemme check.
